version: '3.4'

services:
  pm.iy.emailrouterdemoapp:
    image: ${DOCKER_REGISTRY-}pmiyemailrouterdemoapp
    build:
      context: .
      dockerfile: PM.IY.EmailRouterDemoApp/Dockerfile
    environment:
       - QueueHost=iyc-rabbitmq
       - QueueUserName=guest
       - QueuePassword=guest
       - QueuePort=5672  
       
    depends_on:
      - iyc-rabbitmq   

  iyc-rabbitmq:
    image: "rabbitmq:3-management"
    container_name: iyc-rabbitmq
    ports:
      - 5673:5673
      - 5672:5672
      - 15672:15672