version: '3.4'

services:
  pm.iy.emailrouterdemoapp:
    build:
      context: .
      dockerfile: PM.IY.EmailRouterDemoApp/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https:http://+:80
      - QueueHost=iyc-rabbitmq
      - QueueUserName=guest
      - QueuePassword=guest
      - QueuePort=5672  
    ports:
      - 8000:80
      - 8003:443
      - 5000:5000
      - 5001:5001
    restart: on-failure   
    depends_on:
      - iyc-rabbitmq   

  iyc-rabbitmq:
    image: "rabbitmq:3-management"
    container_name: iyc-rabbitmq
    ports:
      - 5673:5673
      - 5672:5672
      - 15672:15672